### PR TITLE
Update last OVHCloud Api Changes

### PR DESCRIPTION
**Pull request by PhilippeVienne**
Just created a PR to update latest API Specifications from OVHCloud. Is it ok ? Or did I something wrong ?

### CODE REVIEW

**Comment by UrielCh** [comment]
euhhhh

Thx for the PR, but, you should only make a PR containing generator updates...

How did you regen the files, there were some issues in with the current generator, running on the new models...

Can you please check the branch lerna6 that I gonna merge to master?

**Comment by UrielCh** [comment]
my regen differs a lot from yours:

mine:
image

yours:
image

check the number of removed lines.

**Comment by UrielCh** [comment]
Philippe ???

**Comment by PhilippeVienne** [comment]
I used codespace environment, installed workspace packages then run the nom script.

I will recheck that this end of week.

**Comment by UrielCh** [comment]
v4 is out, including big changes.

**Pull request closed without merging**
